# Generated by Django 3.2.4 on 2025-04-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='link',
            field=models.CharField(default='yyy', max_length=200),
            preserve_default=False,
        ),
    ]
